"""add feedback priority, general entity type, real world test run link

Revision ID: ea4064e30555
Revises: ea7b17c08f5f
Create Date: 2026-07-10 20:50:54.762924
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ea4064e30555'
down_revision: Union[str, None] = 'ea7b17c08f5f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Adjusted by hand: autogenerate produced a NOT NULL column with no
    # default, which fails on a table that already has rows (existing
    # feedback would have no value for `priority`). A temporary
    # server_default backfills every existing row to "medium" — the same
    # value the ORM model already uses as its Python-side default for new
    # rows — then the default is dropped so future inserts rely on the
    # ORM/application default (matching how every other defaulted string
    # column in this schema, e.g. review_status, is declared).
    op.add_column(
        'user_feedback',
        sa.Column('priority', sa.String(length=10), nullable=False, server_default='medium'),
    )
    op.alter_column('user_feedback', 'priority', server_default=None)
    op.add_column('user_feedback', sa.Column('real_world_test_run_id', sa.UUID(), nullable=True))
    op.alter_column('user_feedback', 'entity_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.create_index(op.f('ix_user_feedback_priority'), 'user_feedback', ['priority'], unique=False)
    # Named explicitly, matching Postgres's own default naming convention
    # ("{table}_{column}_fkey") already used by every other foreign key in
    # this table's baseline — autogenerate's unnamed form works for
    # upgrade() but leaves Alembic unable to reference the constraint
    # again for downgrade().
    op.create_foreign_key(
        'user_feedback_real_world_test_run_id_fkey',
        'user_feedback', 'real_world_test_runs',
        ['real_world_test_run_id'], ['id'], ondelete='SET NULL',
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        'user_feedback_real_world_test_run_id_fkey', 'user_feedback', type_='foreignkey'
    )
    op.drop_index(op.f('ix_user_feedback_priority'), table_name='user_feedback')
    # NOTE: reverting entity_id to NOT NULL will fail if any "general"
    # (entity_id=NULL) feedback rows were created after this migration
    # was applied — delete or re-assign those rows first if you ever
    # need to roll back past this revision on a database with real data.
    op.alter_column('user_feedback', 'entity_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('user_feedback', 'real_world_test_run_id')
    op.drop_column('user_feedback', 'priority')
    # ### end Alembic commands ###
