"""baseline schema

Captures the full schema as it existed pre-Alembic (every table was
previously created by ``init_database()``'s ``CREATE TABLE IF NOT
EXISTS`` against the ORM metadata — see
``backend/infrastructure/database/session.py``). Verified via
``alembic check`` to exactly match both a fresh database created by this
revision and the project's existing dev database.

- Brand-new deployment: ``alembic upgrade head`` creates this schema.
- Existing deployment (tables already exist via ``create_all``):
  ``alembic stamp head`` records this revision as already applied,
  without re-running any DDL.

All schema changes from this point on should be added as new revisions
(``alembic revision --autogenerate -m "..."``) instead of relying on
``create_all`` to pick up the change.

Revision ID: ea7b17c08f5f
Revises:
Create Date: 2026-07-10 17:05:40.236389
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ea7b17c08f5f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('domain', sa.String(length=255), nullable=True),
    sa.Column('industry', sa.String(length=255), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=True),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'REVIEWER', 'SALES', name='user_role'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_table('audit_logs',
    sa.Column('actor_user_id', sa.UUID(), nullable=True),
    sa.Column('actor_role', sa.String(length=50), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('entity_type', sa.String(length=100), nullable=True),
    sa.Column('entity_id', sa.String(length=100), nullable=True),
    sa.Column('result', sa.String(length=50), nullable=False),
    sa.Column('reason', sa.String(length=500), nullable=True),
    sa.Column('request_id', sa.String(length=64), nullable=True),
    sa.Column('ip_hash', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.String(length=300), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_actor_user_id'), 'audit_logs', ['actor_user_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_entity_id'), 'audit_logs', ['entity_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_entity_type'), 'audit_logs', ['entity_type'], unique=False)
    op.create_index(op.f('ix_audit_logs_result'), 'audit_logs', ['result'], unique=False)
    op.create_table('beta_test_sessions',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('tester_user_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('target_goal', sa.String(length=500), nullable=True),
    sa.Column('total_workflows_tested', sa.Integer(), nullable=False),
    sa.Column('total_drafts_reviewed', sa.Integer(), nullable=False),
    sa.Column('total_feedback_items', sa.Integer(), nullable=False),
    sa.Column('average_quality_score', sa.Float(), nullable=True),
    sa.Column('blockers_count', sa.Integer(), nullable=False),
    sa.Column('bugs_count', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tester_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_beta_test_sessions_status'), 'beta_test_sessions', ['status'], unique=False)
    op.create_table('contacts',
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('first_name', sa.String(length=255), nullable=False),
    sa.Column('last_name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=64), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contacts_company_id'), 'contacts', ['company_id'], unique=False)
    op.create_table('data_retention_policies',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('retention_days', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('dry_run_default', sa.Boolean(), nullable=False),
    sa.Column('created_by_user_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_data_retention_policies_entity_type'), 'data_retention_policies', ['entity_type'], unique=False)
    op.create_table('data_subject_requests',
    sa.Column('request_type', sa.String(length=20), nullable=False),
    sa.Column('subject_email', sa.String(length=320), nullable=True),
    sa.Column('subject_domain', sa.String(length=255), nullable=True),
    sa.Column('subject_name', sa.String(length=200), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('requested_by_user_id', sa.UUID(), nullable=True),
    sa.Column('handled_by_user_id', sa.UUID(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('result_summary', sa.Text(), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['handled_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['requested_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_data_subject_requests_request_type'), 'data_subject_requests', ['request_type'], unique=False)
    op.create_index(op.f('ix_data_subject_requests_status'), 'data_subject_requests', ['status'], unique=False)
    op.create_index(op.f('ix_data_subject_requests_subject_domain'), 'data_subject_requests', ['subject_domain'], unique=False)
    op.create_index(op.f('ix_data_subject_requests_subject_email'), 'data_subject_requests', ['subject_email'], unique=False)
    op.create_table('do_not_contact_entries',
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('domain', sa.String(length=255), nullable=True),
    sa.Column('company_name', sa.String(length=200), nullable=True),
    sa.Column('company_name_normalized', sa.String(length=200), nullable=True),
    sa.Column('reason', sa.String(length=500), nullable=False),
    sa.Column('source', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by_user_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_do_not_contact_entries_company_name_normalized'), 'do_not_contact_entries', ['company_name_normalized'], unique=False)
    op.create_index(op.f('ix_do_not_contact_entries_domain'), 'do_not_contact_entries', ['domain'], unique=False)
    op.create_index(op.f('ix_do_not_contact_entries_email'), 'do_not_contact_entries', ['email'], unique=False)
    op.create_index(op.f('ix_do_not_contact_entries_is_active'), 'do_not_contact_entries', ['is_active'], unique=False)
    op.create_table('email_provider_connections',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.Enum('MOCK', 'GMAIL', 'OUTLOOK', name='email_provider_type'), nullable=False),
    sa.Column('encrypted_access_token', sa.String(length=4000), nullable=True),
    sa.Column('encrypted_refresh_token', sa.String(length=4000), nullable=True),
    sa.Column('token_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('scope', sa.String(length=500), nullable=True),
    sa.Column('external_account_email', sa.String(length=320), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_email_provider_connections_user_id'), 'email_provider_connections', ['user_id'], unique=False)
    op.create_table('icp_profiles',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('target_industries', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('excluded_industries', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('target_company_sizes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('target_locations', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('target_languages', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('target_keywords', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('negative_keywords', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('target_pain_points', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('buying_triggers', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('required_signals', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('excluded_signals', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('buyer_personas', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('preferred_titles', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('excluded_titles', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('minimum_fit_score', sa.Integer(), nullable=False),
    sa.Column('scoring_weights', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by_user_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_icp_profiles_is_active'), 'icp_profiles', ['is_active'], unique=False)
    op.create_index(op.f('ix_icp_profiles_name'), 'icp_profiles', ['name'], unique=False)
    op.create_table('leads',
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('source', sa.Enum('WEBSITE', 'REFERRAL', 'OUTBOUND', 'EVENT', 'OTHER', name='lead_source'), nullable=False),
    sa.Column('status', sa.Enum('NEW', 'CONTACTED', 'QUALIFIED', 'WON', 'LOST', name='lead_status'), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('pipeline_status', sa.Enum('NEW', 'RESEARCH_COMPLETED', 'DRAFT_CREATED', 'IN_REVIEW', 'APPROVED', 'REJECTED', 'ARCHIVED', name='lead_pipeline_status'), nullable=False),
    sa.Column('pipeline_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_leads_company_id'), 'leads', ['company_id'], unique=False)
    op.create_index(op.f('ix_leads_pipeline_status'), 'leads', ['pipeline_status'], unique=False)
    op.create_table('offer_profiles',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('main_value_proposition', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('target_outcome', sa.Text(), nullable=True),
    sa.Column('pain_points_solved', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('key_benefits', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('differentiators', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('proof_points', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('case_study_notes', sa.Text(), nullable=True),
    sa.Column('pricing_notes', sa.Text(), nullable=True),
    sa.Column('call_to_action', sa.String(length=500), nullable=True),
    sa.Column('tone', sa.String(length=50), nullable=False),
    sa.Column('language', sa.String(length=50), nullable=False),
    sa.Column('forbidden_claims', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('required_disclaimers', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by_user_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_offer_profiles_is_active'), 'offer_profiles', ['is_active'], unique=False)
    op.create_index(op.f('ix_offer_profiles_name'), 'offer_profiles', ['name'], unique=False)
    op.create_table('onboarding_statuses',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('current_step', sa.String(length=50), nullable=False),
    sa.Column('completed_steps', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('skipped_steps', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_completed', sa.Boolean(), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_onboarding_statuses_user_id'), 'onboarding_statuses', ['user_id'], unique=True)
    op.create_table('data_retention_runs',
    sa.Column('policy_id', sa.UUID(), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('action', sa.String(length=20), nullable=False),
    sa.Column('dry_run', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('started_by_user_id', sa.UUID(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('total_scanned', sa.Integer(), nullable=False),
    sa.Column('total_eligible', sa.Integer(), nullable=False),
    sa.Column('total_processed', sa.Integer(), nullable=False),
    sa.Column('total_failed', sa.Integer(), nullable=False),
    sa.Column('warnings', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('errors', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['policy_id'], ['data_retention_policies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['started_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_data_retention_runs_policy_id'), 'data_retention_runs', ['policy_id'], unique=False)
    op.create_index(op.f('ix_data_retention_runs_status'), 'data_retention_runs', ['status'], unique=False)
    op.create_table('email_drafts',
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('lead_id', sa.UUID(), nullable=True),
    sa.Column('workflow_run_id', sa.UUID(), nullable=True),
    sa.Column('subject_lines', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('email_body', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('review_status', sa.Enum('NEEDS_REVIEW', 'IN_REVIEW', 'APPROVED', 'REJECTED', 'CHANGES_REQUESTED', 'ARCHIVED', name='email_draft_review_status'), nullable=False),
    sa.Column('reviewer_name', sa.String(length=200), nullable=True),
    sa.Column('review_comment', sa.Text(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_email_drafts_company_id'), 'email_drafts', ['company_id'], unique=False)
    op.create_index(op.f('ix_email_drafts_lead_id'), 'email_drafts', ['lead_id'], unique=False)
    op.create_index(op.f('ix_email_drafts_review_status'), 'email_drafts', ['review_status'], unique=False)
    op.create_index(op.f('ix_email_drafts_workflow_run_id'), 'email_drafts', ['workflow_run_id'], unique=False)
    op.create_table('interactions',
    sa.Column('lead_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.Enum('EMAIL', 'CALL', 'MEETING', 'NOTE', 'WORKFLOW_RUN', name='interaction_type'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_interactions_lead_id'), 'interactions', ['lead_id'], unique=False)
    op.create_table('lead_sourcing_campaigns',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('icp_profile_id', sa.UUID(), nullable=True),
    sa.Column('offer_profile_id', sa.UUID(), nullable=True),
    sa.Column('source_type', sa.String(length=50), nullable=False),
    sa.Column('search_query', sa.Text(), nullable=True),
    sa.Column('target_industry', sa.String(length=200), nullable=True),
    sa.Column('target_location', sa.String(length=200), nullable=True),
    sa.Column('target_keywords', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('excluded_keywords', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('max_results', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_by_user_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['icp_profile_id'], ['icp_profiles.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['offer_profile_id'], ['offer_profiles.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lead_sourcing_campaigns_name'), 'lead_sourcing_campaigns', ['name'], unique=False)
    op.create_index(op.f('ix_lead_sourcing_campaigns_status'), 'lead_sourcing_campaigns', ['status'], unique=False)
    op.create_table('outreach_campaigns',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('icp_profile_id', sa.UUID(), nullable=True),
    sa.Column('offer_profile_id', sa.UUID(), nullable=True),
    sa.Column('target_language', sa.String(length=50), nullable=True),
    sa.Column('tone', sa.String(length=50), nullable=True),
    sa.Column('min_qualification_score', sa.Integer(), nullable=False),
    sa.Column('allowed_qualification_levels', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('excluded_statuses', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('max_queue_items', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_by_user_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['icp_profile_id'], ['icp_profiles.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['offer_profile_id'], ['offer_profiles.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_outreach_campaigns_name'), 'outreach_campaigns', ['name'], unique=False)
    op.create_index(op.f('ix_outreach_campaigns_status'), 'outreach_campaigns', ['status'], unique=False)
    op.create_table('qualification_runs',
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('source_type', sa.String(length=20), nullable=False),
    sa.Column('icp_profile_id', sa.UUID(), nullable=True),
    sa.Column('offer_profile_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('started_by_user_id', sa.UUID(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('total_items', sa.Integer(), nullable=False),
    sa.Column('qualified_count', sa.Integer(), nullable=False),
    sa.Column('priority_count', sa.Integer(), nullable=False),
    sa.Column('disqualified_count', sa.Integer(), nullable=False),
    sa.Column('needs_review_count', sa.Integer(), nullable=False),
    sa.Column('average_score', sa.Float(), nullable=True),
    sa.Column('warnings', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['icp_profile_id'], ['icp_profiles.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['offer_profile_id'], ['offer_profiles.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['started_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_qualification_runs_status'), 'qualification_runs', ['status'], unique=False)
    op.create_table('workflow_runs',
    sa.Column('company_name', sa.String(length=200), nullable=False),
    sa.Column('workflow_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('review_status', sa.Enum('NEEDS_REVIEW', 'REVIEWED', 'APPROVED', 'REJECTED', 'ARCHIVED', name='workflow_review_status'), nullable=False),
    sa.Column('input_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('result_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('missing_information', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('compliance_notes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=True),
    sa.Column('lead_id', sa.UUID(), nullable=True),
    sa.Column('contact_id', sa.UUID(), nullable=True),
    sa.Column('email_draft_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workflow_runs_company_id'), 'workflow_runs', ['company_id'], unique=False)
    op.create_index(op.f('ix_workflow_runs_company_name'), 'workflow_runs', ['company_name'], unique=False)
    op.create_index(op.f('ix_workflow_runs_contact_id'), 'workflow_runs', ['contact_id'], unique=False)
    op.create_index(op.f('ix_workflow_runs_email_draft_id'), 'workflow_runs', ['email_draft_id'], unique=False)
    op.create_index(op.f('ix_workflow_runs_lead_id'), 'workflow_runs', ['lead_id'], unique=False)
    op.create_index(op.f('ix_workflow_runs_review_status'), 'workflow_runs', ['review_status'], unique=False)
    op.create_index(op.f('ix_workflow_runs_workflow_type'), 'workflow_runs', ['workflow_type'], unique=False)
    op.create_table('workspace_settings',
    sa.Column('workspace_name', sa.String(length=200), nullable=False),
    sa.Column('company_name', sa.String(length=200), nullable=True),
    sa.Column('company_website', sa.String(length=500), nullable=True),
    sa.Column('default_language', sa.String(length=10), nullable=False),
    sa.Column('default_tone', sa.String(length=50), nullable=False),
    sa.Column('default_icp_profile_id', sa.UUID(), nullable=True),
    sa.Column('default_offer_profile_id', sa.UUID(), nullable=True),
    sa.Column('require_human_review', sa.Boolean(), nullable=False),
    sa.Column('require_do_not_contact_check', sa.Boolean(), nullable=False),
    sa.Column('allow_real_llm_calls', sa.Boolean(), nullable=False),
    sa.Column('allow_real_email_drafts', sa.Boolean(), nullable=False),
    sa.Column('allow_real_reply_reads', sa.Boolean(), nullable=False),
    sa.Column('allow_real_dispatch', sa.Boolean(), nullable=False),
    sa.Column('dispatch_mode', sa.String(length=20), nullable=False),
    sa.Column('data_retention_enabled', sa.Boolean(), nullable=False),
    sa.Column('anonymize_instead_of_delete', sa.Boolean(), nullable=False),
    sa.Column('data_export_enabled', sa.Boolean(), nullable=False),
    sa.Column('data_subject_requests_enabled', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['default_icp_profile_id'], ['icp_profiles.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['default_offer_profile_id'], ['offer_profiles.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('external_email_drafts',
    sa.Column('email_draft_id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.Enum('MOCK', 'GMAIL', 'OUTLOOK', name='email_provider_type'), nullable=False),
    sa.Column('provider_status', sa.Enum('MOCK_CREATED', 'CREATED', 'BLOCKED', 'FAILED', name='external_draft_provider_status'), nullable=False),
    sa.Column('provider_draft_id', sa.String(length=255), nullable=True),
    sa.Column('provider_draft_url', sa.String(length=2000), nullable=True),
    sa.Column('created_by_user_id', sa.UUID(), nullable=True),
    sa.Column('last_error', sa.String(length=1000), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['email_draft_id'], ['email_drafts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_external_email_drafts_email_draft_id'), 'external_email_drafts', ['email_draft_id'], unique=True)
    op.create_table('lead_sourcing_runs',
    sa.Column('campaign_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('started_by_user_id', sa.UUID(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('total_candidates_found', sa.Integer(), nullable=False),
    sa.Column('total_candidates_saved', sa.Integer(), nullable=False),
    sa.Column('total_duplicates', sa.Integer(), nullable=False),
    sa.Column('total_blocked_by_do_not_contact', sa.Integer(), nullable=False),
    sa.Column('total_errors', sa.Integer(), nullable=False),
    sa.Column('warnings', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['lead_sourcing_campaigns.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['started_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lead_sourcing_runs_campaign_id'), 'lead_sourcing_runs', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_lead_sourcing_runs_status'), 'lead_sourcing_runs', ['status'], unique=False)
    op.create_table('review_events',
    sa.Column('workflow_run_id', sa.UUID(), nullable=True),
    sa.Column('email_draft_id', sa.UUID(), nullable=True),
    sa.Column('event_type', sa.Enum('REVIEW_STARTED', 'COMMENT_ADDED', 'APPROVED', 'REJECTED', 'CHANGES_REQUESTED', 'ARCHIVED', 'BLOCKED', name='review_event_type'), nullable=False),
    sa.Column('previous_status', sa.String(length=50), nullable=True),
    sa.Column('new_status', sa.String(length=50), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('reviewer_name', sa.String(length=200), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['email_draft_id'], ['email_drafts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workflow_run_id'], ['workflow_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_review_events_email_draft_id'), 'review_events', ['email_draft_id'], unique=False)
    op.create_index(op.f('ix_review_events_event_type'), 'review_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_review_events_workflow_run_id'), 'review_events', ['workflow_run_id'], unique=False)
    op.create_table('lead_candidates',
    sa.Column('sourcing_run_id', sa.UUID(), nullable=False),
    sa.Column('campaign_id', sa.UUID(), nullable=False),
    sa.Column('company_name', sa.String(length=200), nullable=True),
    sa.Column('company_domain', sa.String(length=255), nullable=True),
    sa.Column('company_website_url', sa.String(length=2000), nullable=True),
    sa.Column('industry', sa.String(length=200), nullable=True),
    sa.Column('location', sa.String(length=200), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('source_url', sa.String(length=2000), nullable=True),
    sa.Column('source_name', sa.String(length=200), nullable=True),
    sa.Column('source_type', sa.String(length=50), nullable=False),
    sa.Column('public_contact_email', sa.String(length=320), nullable=True),
    sa.Column('contact_page_url', sa.String(length=2000), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('icp_fit_score', sa.Integer(), nullable=True),
    sa.Column('icp_fit_level', sa.String(length=20), nullable=True),
    sa.Column('matched_signals', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('negative_signals', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('do_not_contact_status', sa.String(length=20), nullable=False),
    sa.Column('duplicate_status', sa.String(length=20), nullable=False),
    sa.Column('review_status', sa.String(length=20), nullable=False),
    sa.Column('crm_company_id', sa.UUID(), nullable=True),
    sa.Column('crm_lead_id', sa.UUID(), nullable=True),
    sa.Column('notes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('warnings', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['lead_sourcing_campaigns.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['crm_company_id'], ['companies.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['crm_lead_id'], ['leads.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['sourcing_run_id'], ['lead_sourcing_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lead_candidates_campaign_id'), 'lead_candidates', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_lead_candidates_company_domain'), 'lead_candidates', ['company_domain'], unique=False)
    op.create_index(op.f('ix_lead_candidates_review_status'), 'lead_candidates', ['review_status'], unique=False)
    op.create_index(op.f('ix_lead_candidates_sourcing_run_id'), 'lead_candidates', ['sourcing_run_id'], unique=False)
    op.create_table('replies',
    sa.Column('lead_id', sa.UUID(), nullable=True),
    sa.Column('company_id', sa.UUID(), nullable=True),
    sa.Column('email_draft_id', sa.UUID(), nullable=True),
    sa.Column('external_draft_id', sa.UUID(), nullable=True),
    sa.Column('provider', sa.Enum('MOCK', 'GMAIL', 'OUTLOOK', name='email_provider_type'), nullable=False),
    sa.Column('provider_message_id', sa.String(length=255), nullable=False),
    sa.Column('provider_thread_id', sa.String(length=255), nullable=True),
    sa.Column('provider_message_url', sa.String(length=2000), nullable=True),
    sa.Column('from_email', sa.String(length=320), nullable=False),
    sa.Column('from_name', sa.String(length=200), nullable=True),
    sa.Column('to_email', sa.String(length=320), nullable=True),
    sa.Column('subject', sa.String(length=500), nullable=True),
    sa.Column('body_preview', sa.String(length=500), nullable=True),
    sa.Column('body_text', sa.String(length=20000), nullable=True),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('detected_intent', sa.Enum('INTERESTED', 'MEETING_REQUEST', 'QUESTION', 'OBJECTION', 'NOT_INTERESTED', 'OUT_OF_OFFICE', 'UNCLEAR', name='reply_intent'), nullable=True),
    sa.Column('sentiment', sa.Enum('POSITIVE', 'NEUTRAL', 'NEGATIVE', 'UNCLEAR', name='reply_sentiment'), nullable=True),
    sa.Column('reply_category', sa.Enum('INTERESTED', 'NOT_INTERESTED', 'NEEDS_MORE_INFO', 'MEETING_REQUEST', 'OUT_OF_OFFICE', 'UNSUBSCRIBE', 'UNKNOWN', name='reply_category'), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.Column('last_error', sa.String(length=1000), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['email_draft_id'], ['email_drafts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['external_draft_id'], ['external_email_drafts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'provider_message_id', name='uq_replies_provider_message_id')
    )
    op.create_index(op.f('ix_replies_company_id'), 'replies', ['company_id'], unique=False)
    op.create_index(op.f('ix_replies_email_draft_id'), 'replies', ['email_draft_id'], unique=False)
    op.create_index(op.f('ix_replies_from_email'), 'replies', ['from_email'], unique=False)
    op.create_index(op.f('ix_replies_is_archived'), 'replies', ['is_archived'], unique=False)
    op.create_index(op.f('ix_replies_lead_id'), 'replies', ['lead_id'], unique=False)
    op.create_index(op.f('ix_replies_reply_category'), 'replies', ['reply_category'], unique=False)
    op.create_table('qualification_results',
    sa.Column('qualification_run_id', sa.UUID(), nullable=False),
    sa.Column('lead_candidate_id', sa.UUID(), nullable=True),
    sa.Column('lead_id', sa.UUID(), nullable=True),
    sa.Column('company_id', sa.UUID(), nullable=True),
    sa.Column('icp_profile_id', sa.UUID(), nullable=True),
    sa.Column('offer_profile_id', sa.UUID(), nullable=True),
    sa.Column('qualification_score', sa.Integer(), nullable=False),
    sa.Column('qualification_level', sa.String(length=20), nullable=False),
    sa.Column('qualification_status', sa.String(length=20), nullable=False),
    sa.Column('priority_rank', sa.Integer(), nullable=True),
    sa.Column('fit_summary', sa.Text(), nullable=True),
    sa.Column('score_breakdown', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('positive_signals', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('negative_signals', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('missing_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('recommended_next_action', sa.String(length=30), nullable=False),
    sa.Column('recommended_outreach_angle', sa.Text(), nullable=True),
    sa.Column('disqualification_reason', sa.Text(), nullable=True),
    sa.Column('compliance_status', sa.String(length=20), nullable=False),
    sa.Column('do_not_contact_status', sa.String(length=20), nullable=False),
    sa.Column('duplicate_status', sa.String(length=20), nullable=False),
    sa.Column('pipeline_status', sa.String(length=30), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('reviewed_by_user_id', sa.UUID(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['icp_profile_id'], ['icp_profiles.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['lead_candidate_id'], ['lead_candidates.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['offer_profile_id'], ['offer_profiles.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['qualification_run_id'], ['qualification_runs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewed_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_qualification_results_lead_candidate_id'), 'qualification_results', ['lead_candidate_id'], unique=False)
    op.create_index(op.f('ix_qualification_results_lead_id'), 'qualification_results', ['lead_id'], unique=False)
    op.create_index(op.f('ix_qualification_results_qualification_run_id'), 'qualification_results', ['qualification_run_id'], unique=False)
    op.create_index(op.f('ix_qualification_results_qualification_status'), 'qualification_results', ['qualification_status'], unique=False)
    op.create_table('outreach_queue_items',
    sa.Column('campaign_id', sa.UUID(), nullable=False),
    sa.Column('lead_id', sa.UUID(), nullable=True),
    sa.Column('company_id', sa.UUID(), nullable=True),
    sa.Column('lead_candidate_id', sa.UUID(), nullable=True),
    sa.Column('qualification_result_id', sa.UUID(), nullable=True),
    sa.Column('icp_profile_id', sa.UUID(), nullable=True),
    sa.Column('offer_profile_id', sa.UUID(), nullable=True),
    sa.Column('priority_rank', sa.Integer(), nullable=True),
    sa.Column('qualification_score', sa.Integer(), nullable=False),
    sa.Column('qualification_level', sa.String(length=20), nullable=False),
    sa.Column('queue_status', sa.String(length=30), nullable=False),
    sa.Column('recommended_outreach_angle', sa.Text(), nullable=True),
    sa.Column('personalization_notes', sa.Text(), nullable=True),
    sa.Column('compliance_status', sa.String(length=20), nullable=False),
    sa.Column('do_not_contact_status', sa.String(length=20), nullable=False),
    sa.Column('duplicate_status', sa.String(length=20), nullable=False),
    sa.Column('workflow_run_id', sa.UUID(), nullable=True),
    sa.Column('email_draft_id', sa.UUID(), nullable=True),
    sa.Column('review_id', sa.UUID(), nullable=True),
    sa.Column('external_draft_id', sa.UUID(), nullable=True),
    sa.Column('last_action', sa.String(length=50), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('created_by_user_id', sa.UUID(), nullable=True),
    sa.Column('assigned_to_user_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_to_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['campaign_id'], ['outreach_campaigns.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['email_draft_id'], ['email_drafts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['external_draft_id'], ['external_email_drafts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['icp_profile_id'], ['icp_profiles.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['lead_candidate_id'], ['lead_candidates.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['offer_profile_id'], ['offer_profiles.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['qualification_result_id'], ['qualification_results.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workflow_run_id'], ['workflow_runs.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_outreach_queue_items_campaign_id'), 'outreach_queue_items', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_outreach_queue_items_lead_candidate_id'), 'outreach_queue_items', ['lead_candidate_id'], unique=False)
    op.create_index(op.f('ix_outreach_queue_items_lead_id'), 'outreach_queue_items', ['lead_id'], unique=False)
    op.create_index(op.f('ix_outreach_queue_items_queue_status'), 'outreach_queue_items', ['queue_status'], unique=False)
    op.create_table('outreach_dispatches',
    sa.Column('queue_item_id', sa.UUID(), nullable=False),
    sa.Column('outreach_campaign_id', sa.UUID(), nullable=True),
    sa.Column('lead_id', sa.UUID(), nullable=True),
    sa.Column('company_id', sa.UUID(), nullable=True),
    sa.Column('email_draft_id', sa.UUID(), nullable=True),
    sa.Column('external_draft_id', sa.UUID(), nullable=True),
    sa.Column('review_id', sa.UUID(), nullable=True),
    sa.Column('provider', sa.String(length=20), nullable=False),
    sa.Column('dispatch_mode', sa.String(length=20), nullable=False),
    sa.Column('dispatch_status', sa.String(length=30), nullable=False),
    sa.Column('recipient_email', sa.String(length=320), nullable=True),
    sa.Column('subject_snapshot', sa.String(length=500), nullable=True),
    sa.Column('body_preview_snapshot', sa.String(length=600), nullable=True),
    sa.Column('final_confirmation_by_user_id', sa.UUID(), nullable=True),
    sa.Column('final_confirmation_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('compliance_acknowledged_by_user_id', sa.UUID(), nullable=True),
    sa.Column('compliance_acknowledged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('do_not_contact_checked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('human_review_checked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('provider_message_id', sa.String(length=255), nullable=True),
    sa.Column('provider_draft_id', sa.String(length=255), nullable=True),
    sa.Column('provider_url', sa.String(length=2000), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('created_by_user_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['compliance_acknowledged_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['email_draft_id'], ['email_drafts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['external_draft_id'], ['external_email_drafts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['final_confirmation_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['outreach_campaign_id'], ['outreach_campaigns.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['queue_item_id'], ['outreach_queue_items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_outreach_dispatches_dispatch_status'), 'outreach_dispatches', ['dispatch_status'], unique=False)
    op.create_index(op.f('ix_outreach_dispatches_queue_item_id'), 'outreach_dispatches', ['queue_item_id'], unique=False)
    op.create_table('quality_scores',
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('score_total', sa.Integer(), nullable=False),
    sa.Column('score_level', sa.String(length=20), nullable=False),
    sa.Column('score_breakdown', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('strengths', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('weaknesses', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('warnings', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('recommended_improvements', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('compliance_flags', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('evaluated_by', sa.String(length=20), nullable=False),
    sa.Column('evaluated_by_user_id', sa.UUID(), nullable=True),
    sa.Column('provider', sa.String(length=20), nullable=False),
    sa.Column('workflow_run_id', sa.UUID(), nullable=True),
    sa.Column('email_draft_id', sa.UUID(), nullable=True),
    sa.Column('lead_id', sa.UUID(), nullable=True),
    sa.Column('company_id', sa.UUID(), nullable=True),
    sa.Column('lead_candidate_id', sa.UUID(), nullable=True),
    sa.Column('qualification_result_id', sa.UUID(), nullable=True),
    sa.Column('outreach_queue_item_id', sa.UUID(), nullable=True),
    sa.Column('reply_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['email_draft_id'], ['email_drafts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['evaluated_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['lead_candidate_id'], ['lead_candidates.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['outreach_queue_item_id'], ['outreach_queue_items.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['qualification_result_id'], ['qualification_results.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['reply_id'], ['replies.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workflow_run_id'], ['workflow_runs.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quality_scores_entity_id'), 'quality_scores', ['entity_id'], unique=False)
    op.create_index(op.f('ix_quality_scores_entity_type'), 'quality_scores', ['entity_type'], unique=False)
    op.create_index(op.f('ix_quality_scores_score_level'), 'quality_scores', ['score_level'], unique=False)
    op.create_table('user_feedback',
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('feedback_type', sa.String(length=30), nullable=False),
    sa.Column('feedback_text', sa.Text(), nullable=True),
    sa.Column('issue_tags', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('improvement_tags', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_blocking', sa.Boolean(), nullable=False),
    sa.Column('workflow_run_id', sa.UUID(), nullable=True),
    sa.Column('email_draft_id', sa.UUID(), nullable=True),
    sa.Column('lead_id', sa.UUID(), nullable=True),
    sa.Column('company_id', sa.UUID(), nullable=True),
    sa.Column('lead_candidate_id', sa.UUID(), nullable=True),
    sa.Column('qualification_result_id', sa.UUID(), nullable=True),
    sa.Column('outreach_queue_item_id', sa.UUID(), nullable=True),
    sa.Column('reply_id', sa.UUID(), nullable=True),
    sa.Column('submitted_by_user_id', sa.UUID(), nullable=True),
    sa.Column('reviewed_by_user_id', sa.UUID(), nullable=True),
    sa.Column('review_status', sa.String(length=20), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['email_draft_id'], ['email_drafts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['lead_candidate_id'], ['lead_candidates.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['outreach_queue_item_id'], ['outreach_queue_items.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['qualification_result_id'], ['qualification_results.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['reply_id'], ['replies.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['reviewed_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['submitted_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workflow_run_id'], ['workflow_runs.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_feedback_entity_id'), 'user_feedback', ['entity_id'], unique=False)
    op.create_index(op.f('ix_user_feedback_entity_type'), 'user_feedback', ['entity_type'], unique=False)
    op.create_index(op.f('ix_user_feedback_feedback_type'), 'user_feedback', ['feedback_type'], unique=False)
    op.create_index(op.f('ix_user_feedback_is_blocking'), 'user_feedback', ['is_blocking'], unique=False)
    op.create_index(op.f('ix_user_feedback_review_status'), 'user_feedback', ['review_status'], unique=False)
    op.create_table('real_world_test_runs',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('mode', sa.String(length=20), nullable=False),
    sa.Column('lead_candidate_id', sa.UUID(), nullable=True),
    sa.Column('lead_id', sa.UUID(), nullable=True),
    sa.Column('icp_profile_id', sa.UUID(), nullable=True),
    sa.Column('offer_profile_id', sa.UUID(), nullable=True),
    sa.Column('workflow_run_id', sa.UUID(), nullable=True),
    sa.Column('quality_score_id', sa.UUID(), nullable=True),
    sa.Column('input_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('result_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('warnings', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('errors', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_by_user_id', sa.UUID(), nullable=True),
    sa.Column('aborted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['icp_profile_id'], ['icp_profiles.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['lead_candidate_id'], ['lead_candidates.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['offer_profile_id'], ['offer_profiles.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['quality_score_id'], ['quality_scores.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workflow_run_id'], ['workflow_runs.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_real_world_test_runs_status'), 'real_world_test_runs', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_real_world_test_runs_status'), table_name='real_world_test_runs')
    op.drop_table('real_world_test_runs')
    op.drop_index(op.f('ix_user_feedback_review_status'), table_name='user_feedback')
    op.drop_index(op.f('ix_user_feedback_is_blocking'), table_name='user_feedback')
    op.drop_index(op.f('ix_user_feedback_feedback_type'), table_name='user_feedback')
    op.drop_index(op.f('ix_user_feedback_entity_type'), table_name='user_feedback')
    op.drop_index(op.f('ix_user_feedback_entity_id'), table_name='user_feedback')
    op.drop_table('user_feedback')
    op.drop_index(op.f('ix_quality_scores_score_level'), table_name='quality_scores')
    op.drop_index(op.f('ix_quality_scores_entity_type'), table_name='quality_scores')
    op.drop_index(op.f('ix_quality_scores_entity_id'), table_name='quality_scores')
    op.drop_table('quality_scores')
    op.drop_index(op.f('ix_outreach_dispatches_queue_item_id'), table_name='outreach_dispatches')
    op.drop_index(op.f('ix_outreach_dispatches_dispatch_status'), table_name='outreach_dispatches')
    op.drop_table('outreach_dispatches')
    op.drop_index(op.f('ix_outreach_queue_items_queue_status'), table_name='outreach_queue_items')
    op.drop_index(op.f('ix_outreach_queue_items_lead_id'), table_name='outreach_queue_items')
    op.drop_index(op.f('ix_outreach_queue_items_lead_candidate_id'), table_name='outreach_queue_items')
    op.drop_index(op.f('ix_outreach_queue_items_campaign_id'), table_name='outreach_queue_items')
    op.drop_table('outreach_queue_items')
    op.drop_index(op.f('ix_qualification_results_qualification_status'), table_name='qualification_results')
    op.drop_index(op.f('ix_qualification_results_qualification_run_id'), table_name='qualification_results')
    op.drop_index(op.f('ix_qualification_results_lead_id'), table_name='qualification_results')
    op.drop_index(op.f('ix_qualification_results_lead_candidate_id'), table_name='qualification_results')
    op.drop_table('qualification_results')
    op.drop_index(op.f('ix_replies_reply_category'), table_name='replies')
    op.drop_index(op.f('ix_replies_lead_id'), table_name='replies')
    op.drop_index(op.f('ix_replies_is_archived'), table_name='replies')
    op.drop_index(op.f('ix_replies_from_email'), table_name='replies')
    op.drop_index(op.f('ix_replies_email_draft_id'), table_name='replies')
    op.drop_index(op.f('ix_replies_company_id'), table_name='replies')
    op.drop_table('replies')
    op.drop_index(op.f('ix_lead_candidates_sourcing_run_id'), table_name='lead_candidates')
    op.drop_index(op.f('ix_lead_candidates_review_status'), table_name='lead_candidates')
    op.drop_index(op.f('ix_lead_candidates_company_domain'), table_name='lead_candidates')
    op.drop_index(op.f('ix_lead_candidates_campaign_id'), table_name='lead_candidates')
    op.drop_table('lead_candidates')
    op.drop_index(op.f('ix_review_events_workflow_run_id'), table_name='review_events')
    op.drop_index(op.f('ix_review_events_event_type'), table_name='review_events')
    op.drop_index(op.f('ix_review_events_email_draft_id'), table_name='review_events')
    op.drop_table('review_events')
    op.drop_index(op.f('ix_lead_sourcing_runs_status'), table_name='lead_sourcing_runs')
    op.drop_index(op.f('ix_lead_sourcing_runs_campaign_id'), table_name='lead_sourcing_runs')
    op.drop_table('lead_sourcing_runs')
    op.drop_index(op.f('ix_external_email_drafts_email_draft_id'), table_name='external_email_drafts')
    op.drop_table('external_email_drafts')
    op.drop_table('workspace_settings')
    op.drop_index(op.f('ix_workflow_runs_workflow_type'), table_name='workflow_runs')
    op.drop_index(op.f('ix_workflow_runs_review_status'), table_name='workflow_runs')
    op.drop_index(op.f('ix_workflow_runs_lead_id'), table_name='workflow_runs')
    op.drop_index(op.f('ix_workflow_runs_email_draft_id'), table_name='workflow_runs')
    op.drop_index(op.f('ix_workflow_runs_contact_id'), table_name='workflow_runs')
    op.drop_index(op.f('ix_workflow_runs_company_name'), table_name='workflow_runs')
    op.drop_index(op.f('ix_workflow_runs_company_id'), table_name='workflow_runs')
    op.drop_table('workflow_runs')
    op.drop_index(op.f('ix_qualification_runs_status'), table_name='qualification_runs')
    op.drop_table('qualification_runs')
    op.drop_index(op.f('ix_outreach_campaigns_status'), table_name='outreach_campaigns')
    op.drop_index(op.f('ix_outreach_campaigns_name'), table_name='outreach_campaigns')
    op.drop_table('outreach_campaigns')
    op.drop_index(op.f('ix_lead_sourcing_campaigns_status'), table_name='lead_sourcing_campaigns')
    op.drop_index(op.f('ix_lead_sourcing_campaigns_name'), table_name='lead_sourcing_campaigns')
    op.drop_table('lead_sourcing_campaigns')
    op.drop_index(op.f('ix_interactions_lead_id'), table_name='interactions')
    op.drop_table('interactions')
    op.drop_index(op.f('ix_email_drafts_workflow_run_id'), table_name='email_drafts')
    op.drop_index(op.f('ix_email_drafts_review_status'), table_name='email_drafts')
    op.drop_index(op.f('ix_email_drafts_lead_id'), table_name='email_drafts')
    op.drop_index(op.f('ix_email_drafts_company_id'), table_name='email_drafts')
    op.drop_table('email_drafts')
    op.drop_index(op.f('ix_data_retention_runs_status'), table_name='data_retention_runs')
    op.drop_index(op.f('ix_data_retention_runs_policy_id'), table_name='data_retention_runs')
    op.drop_table('data_retention_runs')
    op.drop_index(op.f('ix_onboarding_statuses_user_id'), table_name='onboarding_statuses')
    op.drop_table('onboarding_statuses')
    op.drop_index(op.f('ix_offer_profiles_name'), table_name='offer_profiles')
    op.drop_index(op.f('ix_offer_profiles_is_active'), table_name='offer_profiles')
    op.drop_table('offer_profiles')
    op.drop_index(op.f('ix_leads_pipeline_status'), table_name='leads')
    op.drop_index(op.f('ix_leads_company_id'), table_name='leads')
    op.drop_table('leads')
    op.drop_index(op.f('ix_icp_profiles_name'), table_name='icp_profiles')
    op.drop_index(op.f('ix_icp_profiles_is_active'), table_name='icp_profiles')
    op.drop_table('icp_profiles')
    op.drop_index(op.f('ix_email_provider_connections_user_id'), table_name='email_provider_connections')
    op.drop_table('email_provider_connections')
    op.drop_index(op.f('ix_do_not_contact_entries_is_active'), table_name='do_not_contact_entries')
    op.drop_index(op.f('ix_do_not_contact_entries_email'), table_name='do_not_contact_entries')
    op.drop_index(op.f('ix_do_not_contact_entries_domain'), table_name='do_not_contact_entries')
    op.drop_index(op.f('ix_do_not_contact_entries_company_name_normalized'), table_name='do_not_contact_entries')
    op.drop_table('do_not_contact_entries')
    op.drop_index(op.f('ix_data_subject_requests_subject_email'), table_name='data_subject_requests')
    op.drop_index(op.f('ix_data_subject_requests_subject_domain'), table_name='data_subject_requests')
    op.drop_index(op.f('ix_data_subject_requests_status'), table_name='data_subject_requests')
    op.drop_index(op.f('ix_data_subject_requests_request_type'), table_name='data_subject_requests')
    op.drop_table('data_subject_requests')
    op.drop_index(op.f('ix_data_retention_policies_entity_type'), table_name='data_retention_policies')
    op.drop_table('data_retention_policies')
    op.drop_index(op.f('ix_contacts_company_id'), table_name='contacts')
    op.drop_table('contacts')
    op.drop_index(op.f('ix_beta_test_sessions_status'), table_name='beta_test_sessions')
    op.drop_table('beta_test_sessions')
    op.drop_index(op.f('ix_audit_logs_result'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_entity_type'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_entity_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_actor_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('companies')
    # ### end Alembic commands ###
